In [10]:
import pandas as pd
import json
csv = "full_drinks_cleaning.csv"

In [11]:
glass_df = pd.read_csv(csv)
glass_df

,Name,Ingredient 1,Ingredient 2,Ingredient 3,Ingredient 4,Ingredient 5,Ingredient 6,Ingredient 7,Ingredient 8,Ingredient 9,Measurement 1,Measurement 2,Measurement 3,Measurement 4,Measurement 5,Measurement 6,Measurement 7,Measurement 8,Measurement 9
0,3-Mile Long Island Iced Tea,Gin,Light rum,Tequila,Triple sec,Vodka,Coca-Cola,Sweet and sour,Bitters,Lemon,0.5,0.5,0.5,0.5,0.5,0.5,0.01,NaN,NaN
1,410 Gone,Peach Vodka,Coca-Cola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,50/50,Vanilla vodka,Grand Marnier,Orange juice,NaN,NaN,NaN,NaN,NaN,NaN,2.5,0.5,9,NaN,NaN,NaN,NaN,NaN,NaN
3,501 Blue,Blue Curacao,Blueberry schnapps,Vodka,Sour mix,7-Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,69 Special,Gin,7-Up,Lemon juice,NaN,NaN,NaN,NaN,NaN,NaN,2,4,0.75,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,Vesper,Gin,Vodka,Lillet Blanc,NaN,NaN,NaN,NaN,NaN,NaN,6,1.5,0.75,NaN,NaN,NaN,NaN,NaN,NaN
388,Yellow Bird,White Rum,Galliano,Triple Sec,Lime Juice,NaN,NaN,NaN,NaN,NaN,3,1.5,1.5,1.5,NaN,NaN,NaN,NaN,NaN
389,Zippy's Revenge,Amaretto,Rum,Kool-Aid,NaN,NaN,NaN,NaN,NaN,NaN,2,2,4,NaN,NaN,NaN,NaN,NaN,NaN
390,Zombie,Rum,Gold rum,151 proof rum,Pernod,Grenadine,Lime Juice,Angostura Bitters,NaN,NaN,1.5,1.5,1,0.1,0.1,0.1,0.001,NaN,NaN
391,Zorbatini,Vodka,Ouzo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.25,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
#glass_df = glass_df.drop(['Unnamed: 0','Glass', 'Instructions', 'Ingredient 10', 'Ingredient 11', 'Ingredient 12', 'Ingredient 13', 'Ingredient 14', 'Ingredient 15', 'Measuremnt 10', 'Measurement 11', 'Measurement 12', 'Measurement 13', 'Measurement 14', 'Measurement 15', 'Image URL'], axis=1)
#glass_df

In [15]:
result = glass_df.to_json("glass.json", orient="index")

In [14]:
type(result)

str

AttributeError: 'str' object has no attribute 'to_json'

In [ ]:
drink_l = []
for index, row in glass_df.iterrows():
    drink_d = {"drink": []}